name: Manual Rollback Trigger

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to rollback'
        required: true
        type: choice
        options:
          - staging
          - production
      target_version:
        description: 'Version to rollback to (leave empty for previous successful version)'
        required: false
        type: string
      dry_run:
        description: 'Perform dry run (preview changes without executing)'
        required: false
        type: boolean
        default: false
      reason:
        description: 'Reason for rollback'
        required: false
        type: string
        default: 'Manual rollback requested'

jobs:
  trigger-rollback:
    name: Trigger Rollback Workflow
    runs-on: ubuntu-latest
    
    steps:
      - name: Validate inputs
        run: |
          echo "🔍 Rollback Request Details:"
          echo "Environment: ${{ inputs.environment }}"
          echo "Target Version: ${{ inputs.target_version || 'Previous successful version' }}"
          echo "Dry Run: ${{ inputs.dry_run }}"
          echo "Reason: ${{ inputs.reason }}"
          echo "Requested By: ${{ github.actor }}"

      - name: Trigger rollback workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/rollback.yml/dispatches \
            -d '{
              "ref": "${{ github.ref }}",
              "inputs": {
                "environment": "${{ inputs.environment }}",
                "target_version": "${{ inputs.target_version }}",
                "trigger_reason": "${{ inputs.reason }}",
                "dry_run": "${{ inputs.dry_run }}"
              }
            }'
          
          echo "✅ Rollback workflow triggered successfully"
          echo "Check the Actions tab to monitor the rollback progress"